title: Game Library
email: your-email@example.com
description: "Top 10 sport games of all time"
destination: docs
baseurl: "/game-library"
url: "/game-library"
twitter_username: top10games
github_username: top10games

# Collections
collections:
  games:
    output: true
collections_dir: my_collections

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

exclude:
  - docs
  - Gemfile
  - Gemfile.lock
  - node_modules
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - package.json
  - package-lock.json
  - gulpfile.js
  - theme-personal
